name: Generate TOC

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-toc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate TOC
        run: |
          find . -type d -not -path '*/\.*' | while read dir; do
            if [ "$(ls -A $dir/*.md 2>/dev/null)" ]; then
              echo "# Table of Contents" > $dir/index.md
              for file in $dir/*.md; do
                filename=$(basename "$file")
                echo "- [${filename%.md}]($filename)" >> $dir/index.md
              done
            fi
          done

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m 'chore: Add table of contents to subdirectories'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
